.PHONY: all clean goget gorun {{.BinaryName}}



GOPATH := ${PWD}/.workspace
PATH := ${PATH}:${PWD}/.workspace/bin:${PWD}/bin
export GOPATH
export PATH



all: goget {{.BinaryName}}

clean:
	@rm -rf .workspace/

goget:
	@# Setup workspace.
	@mkdir -p ${PWD}/.workspace/src/github.com/xh3b4sd/
	@ln -fs ${PWD} ${PWD}/.workspace/src/github.com/xh3b4sd/
	@# Fetch the rest of the project dependencies.
	@go get -d -v ./...

gorun:
	@go run \
		main.go



{{.BinaryName}}:
	@go build \
		-o .workspace/bin/{{.BinaryName}} \
		github.com/xh3b4sd/{{.BinaryName}}
