package main

// This file is generated by loader. Don't edit it manually. It is recommended
// to run loader via go generate. To do so put the following comment into your
// go source code and run go generate within your build process.
//
//     //go:generate loader generate
//
// For more information about the usage of loader check the help usage. For
// more information on go generate see
// https://golang.org/cmd/go/#hdr-Generate_Go_files_by_processing_source.
//

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
)

// loaderGeneratedAssetMapVarName contains all loaded files. Map keys are file names. Map values
// are file contents.
var loaderGeneratedAssetMapVarName = map[string][]byte{
	"template/Makefile.tmpl": {31, 139, 8, 0, 0, 9, 110, 136, 0, 255, 148, 145, 65, 75, 3, 49, 16, 133, 207, 59, 191, 98, 160, 94, 55, 57, 232, 105, 65, 104, 69, 180, 167, 182, 96, 65, 4, 47, 217, 236, 52, 27, 155, 77, 150, 36, 171, 149, 178, 255, 93, 18, 91, 169, 173, 23, 111, 147, 204, 123, 201, 55, 111, 216, 106, 190, 92, 188, 84, 40, 140, 65, 105, 72, 88, 84, 78, 81, 68, 229, 252, 96, 113, 191, 103, 119, 218, 10, 255, 185, 16, 29, 141, 35, 0, 192, 227, 114, 53, 91, 207, 177, 186, 197, 171, 253, 234, 249, 126, 228, 236, 195, 249, 109, 232, 133, 36, 56, 233, 204, 214, 243, 177, 186, 80, 240, 90, 219, 227, 109, 173, 45, 208, 174, 119, 62, 226, 247, 155, 199, 83, 174, 1, 64, 24, 83, 29, 104, 46, 56, 50, 106, 5, 197, 212, 119, 88, 250, 13, 158, 124, 1, 144, 61, 169, 57, 193, 39, 138, 67, 143, 63, 77, 6, 197, 180, 219, 54, 218, 99, 217, 95, 242, 243, 224, 37, 87, 58, 182, 67, 205, 164, 235, 248, 174, 189, 174, 111, 66, 195, 161, 152, 26, 139, 229, 38, 28, 44, 255, 114, 78, 240, 129, 162, 108, 49, 182, 132, 158, 66, 68, 183, 201, 117, 239, 221, 27, 201, 136, 13, 245, 100, 27, 178, 82, 83, 72, 120, 202, 97, 154, 184, 108, 176, 124, 71, 198, 25, 99, 105, 32, 63, 228, 105, 149, 195, 180, 150, 87, 40, 138, 78, 104, 203, 148, 75, 65, 157, 165, 115, 16, 214, 131, 54, 77, 150, 150, 14, 127, 175, 128, 159, 57, 178, 234, 15, 252, 243, 216, 191, 2, 0, 0, 255, 255, 91, 69, 5, 105, 45, 2, 0, 0},
	"template/main.go.tmpl":  {31, 139, 8, 0, 0, 9, 110, 136, 0, 255, 42, 72, 76, 206, 78, 76, 79, 85, 200, 77, 204, 204, 227, 226, 202, 204, 45, 200, 47, 42, 81, 208, 224, 226, 84, 74, 203, 45, 81, 226, 210, 228, 226, 74, 43, 205, 75, 6, 203, 106, 104, 42, 84, 115, 113, 166, 229, 150, 232, 5, 20, 101, 230, 149, 164, 105, 40, 121, 164, 230, 228, 228, 43, 132, 231, 23, 229, 164, 196, 228, 41, 105, 114, 213, 114, 1, 2, 0, 0, 255, 255, 77, 130, 136, 165, 78, 0, 0, 0},
}

// LoaderReadFile returns the content of the loaded asset
// associated to assetName. If the requested asset does not exist, an error is
// returned.
func LoaderReadFile(assetName string) ([]byte, error) {
	if v, ok := loaderGeneratedAssetMapVarName[assetName]; ok {
		b := bytes.NewBuffer(v)
		r, err := gzip.NewReader(b)
		if err != nil {
			return nil, err
		}
		var raw bytes.Buffer
		io.Copy(&raw, r)
		r.Close()
		return raw.Bytes(), nil
	}

	return nil, fmt.Errorf("asset not found: %s", assetName)
}

// LoaderFileNames returns a list of file names of all loaded
// assets.
func LoaderFileNames() []string {
	var newFileNames []string

	for fileName := range loaderGeneratedAssetMapVarName {
		newFileNames = append(newFileNames, fileName)
	}

	return newFileNames
}
